---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
{{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
{{- end }}
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          exec:
            command:
            - sh
            - -c
            - curl --http0.9 http://localhost:80/healthcheck | grep 'OK'
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          exec:
            command:
            - sh
            - -c
            - curl --http0.9 http://localhost:80/ | grep 'Well'
        ports:
        - name: public
          containerPort: 80
